version: "3"

services:
  front:
    build:
      context: ./
      dockerfile: DockerfileProd
    ports:
      - 8081:8081
    depends_on:
      - api
  api:
    build:
      context: ./server
    ports:
      - 3035:3035
    depends_on:
      - db
  db:
    image: mongo:latest
    command: mongod --smallfiles --logpath=/dev/null
