version: "3"

services:
  app:
    build: ./server
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - 3030:3030
    depends_on:
      - db
      - front
  front:
    build: .
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - 3031:3031
  db:
    image: mongo:latest
    volumes:
      - ./node_modules/.cache/mongo/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
